### ISSUE TITLE
Question: How to unsubscribe and clean resources got during subscription ?

### ISSUE THREAD

**Issue by achilsowa** [taion/graphql-relay-subscription#288]
Hi, Good job with this small lib. For someone used to `mutationWithClientMutationId`, this is just great.

I've been going through the definition and make some test, but I definitely don't see where to unbscribe and subscribption resources.
I expected to find as a field, just after subscribe, but nothing.

So help
Thanks

**Comment by achilsowa** [comment]
> Hi, Good job with this small lib. For someone used to `mutationWithClientMutationId`, this is just great.
> 
> I've been going through the definition and make some test, but I definitely don't see where to unbscribe and subscribption resources.
> I expected to find as a field, just after subscribe, but nothing.
> 
> So help
> Thanks

I went through your code (one file actually), and I realize my question may be out of the scope of your tool.

But I'll just add another one. 
How actually do we send subscription result back to the client ?
In other word since resolve is not automatically called like for query and mutation, when is resolve actually called in the case of 
subscription and how do we trigger this call ?

Thanks

**Comment by taion** [comment]
Yeah, you end up needing something additional for this. Take a look at e.g. https://github.com/4Catalyzer/graphql-subscription-server/pull/353/files#diff-5474eabd8103965599e37c3698c48d54a466e45e9e0370a2b99b71cd81f76024 or https://github.com/relay-tools/relay-subscriptions/blob/a26869ba2e268a345eb41a8e362a4d2a9780c4a9/examples/todo/data/schema.js#L36.
